/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;


public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMenu = new javax.swing.JDialog();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelMembers = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAccount = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        jTextFieldEmailMember = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAccount = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jRadioButtonAdministrator = new javax.swing.JRadioButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMember = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddMember = new javax.swing.JButton();
        jButtonUpdateMember = new javax.swing.JButton();
        jButtonDeleteMember = new javax.swing.JButton();
        jLabelErrorMember = new javax.swing.JLabel();
        jButtonLogout1 = new javax.swing.JButton();
        jPanelBookings = new javax.swing.JPanel();
        jLabelBookingTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBooking = new javax.swing.JTable();
        jButtonDeleteBooking = new javax.swing.JButton();
        jLabelErrorBooking = new javax.swing.JLabel();
        jButtonLogout2 = new javax.swing.JButton();
        jPanelBins = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMerge = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableBin = new javax.swing.JTable();
        jButtonAddBin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jLabelName2 = new javax.swing.JLabel();
        jTextFieldIdBin = new javax.swing.JTextField();
        jLabelDni2 = new javax.swing.JLabel();
        jLabelErrorBin = new javax.swing.JLabel();
        jButtonLogout3 = new javax.swing.JButton();
        jPanelAccounts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAccount = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonLogout4 = new javax.swing.JButton();
        jPanelBlack = new javax.swing.JPanel();
        jPanelOrange = new javax.swing.JPanel();
        jLabelLoginTitle = new javax.swing.JLabel();
        jPanelWhite = new javax.swing.JPanel();
        jPasswordFieldPasswordLogin = new javax.swing.JPasswordField();
        jTextFieldEmailLogin = new javax.swing.JTextField();
        jButtonSubmitLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelErrorMessage = new javax.swing.JLabel();

        jDialogMenu.setTitle("ADMINISTRATION");
        jDialogMenu.setBackground(new java.awt.Color(219, 139, 34));
        jDialogMenu.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jDialogMenu.setMinimumSize(new java.awt.Dimension(1000, 700));
        jDialogMenu.setResizable(false);

        jTabbedPaneMenu.setBackground(new java.awt.Color(219, 139, 34));
        jTabbedPaneMenu.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPaneMenu.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTabbedPaneMenu.setMinimumSize(new java.awt.Dimension(35, 74));
        jTabbedPaneMenu.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanelMembers.setBackground(new java.awt.Color(244, 164, 12));
        jPanelMembers.setToolTipText("");
        jPanelMembers.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jPanelMembers.setMinimumSize(new java.awt.Dimension(496, 335));
        jPanelMembers.setName(""); // NOI18N
        jPanelMembers.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAccount.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelAccount.setText("ACCOUNT");

        jTextFieldSurname.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabelSurname.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelSurname.setText("SURNAME");

        jTextFieldEmailMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jTextFieldDni.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabelName.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelName.setText("NAME");

        jTextFieldName.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jTextFieldAccount.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelEmail.setText("EMAIL");

        jLabelDni.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelDni.setText("DNI");

        jLabelPassword.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelPassword.setText("PASSWORD");

        jRadioButtonAdministrator.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAdministrator.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jRadioButtonAdministrator.setText("ADMINISTRADOR");

        jPasswordFieldPassword.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmailMember, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabelSurname)
                        .addGap(14, 14, 14)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButtonAdministrator))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname)
                    .addComponent(jRadioButtonAdministrator))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmailMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelAccount)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTableMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMember.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableMember);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEMBERS");

        jButtonAddMember.setBackground(new java.awt.Color(219, 139, 34));
        jButtonAddMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButtonAddMember.setText("ADD");
        jButtonAddMember.setActionCommand("ADD_MEMBER");
        jButtonAddMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddMember.setFocusable(false);

        jButtonUpdateMember.setBackground(new java.awt.Color(219, 139, 34));
        jButtonUpdateMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButtonUpdateMember.setText("UPDATE");
        jButtonUpdateMember.setActionCommand("TAKE");
        jButtonUpdateMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdateMember.setFocusable(false);

        jButtonDeleteMember.setBackground(new java.awt.Color(219, 139, 34));
        jButtonDeleteMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButtonDeleteMember.setText("DELETE");
        jButtonDeleteMember.setActionCommand("DELETE_MEMBER");
        jButtonDeleteMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteMember.setFocusable(false);

        jLabelErrorMember.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jButtonLogout1.setText("Logout");
        jButtonLogout1.setActionCommand("LOGOUT");

        javax.swing.GroupLayout jPanelMembersLayout = new javax.swing.GroupLayout(jPanelMembers);
        jPanelMembers.setLayout(jPanelMembersLayout);
        jPanelMembersLayout.setHorizontalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLogout1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMembersLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(354, 354, 354))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMembersLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)))))
            .addGroup(jPanelMembersLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButtonAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonUpdateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabelErrorMember, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMembersLayout.setVerticalGroup(
            jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMembersLayout.createSequentialGroup()
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMembersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanelMembersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogout1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUpdateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelErrorMember, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Members", jPanelMembers);

        jPanelBookings.setBackground(new java.awt.Color(244, 164, 12));
        jPanelBookings.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jPanelBookings.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabelBookingTitle.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabelBookingTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBookingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBookingTitle.setText("BOOKINGS");

        jTableBooking.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBooking.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableBooking);

        jButtonDeleteBooking.setBackground(new java.awt.Color(219, 139, 34));
        jButtonDeleteBooking.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButtonDeleteBooking.setText("DELETE");
        jButtonDeleteBooking.setActionCommand("DELETE_BOOKING");
        jButtonDeleteBooking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteBooking.setFocusable(false);

        jLabelErrorBooking.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jButtonLogout2.setText("Logout");
        jButtonLogout2.setActionCommand("LOGOUT");

        javax.swing.GroupLayout jPanelBookingsLayout = new javax.swing.GroupLayout(jPanelBookings);
        jPanelBookings.setLayout(jPanelBookingsLayout);
        jPanelBookingsLayout.setHorizontalGroup(
            jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabelBookingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButtonDeleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabelErrorBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogout2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBookingsLayout.setVerticalGroup(
            jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonLogout2)
                .addGap(18, 18, 18)
                .addComponent(jLabelBookingTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Bookings", jPanelBookings);

        jPanelBins.setBackground(new java.awt.Color(244, 164, 12));
        jPanelBins.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jPanelBins.setPreferredSize(new java.awt.Dimension(1000, 500));

        jTableMerge.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTableMerge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMerge.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMerge);

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BINS");

        jTableBin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTableBin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBin.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTableBin);

        jButtonAddBin.setBackground(new java.awt.Color(219, 139, 34));
        jButtonAddBin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButtonAddBin.setText("ADD");
        jButtonAddBin.setActionCommand("ADD_BIN");
        jButtonAddBin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddBin.setFocusable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldCapacity.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabelName2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelName2.setText("CAPACITY");

        jTextFieldIdBin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabelDni2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabelDni2.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDni2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdBin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDni2)
                    .addComponent(jLabelName2)
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabelErrorBin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jButtonLogout3.setText("Logout");
        jButtonLogout3.setActionCommand("LOGOUT");

        javax.swing.GroupLayout jPanelBinsLayout = new javax.swing.GroupLayout(jPanelBins);
        jPanelBins.setLayout(jPanelBinsLayout);
        jPanelBinsLayout.setHorizontalGroup(
            jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBinsLayout.createSequentialGroup()
                .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBinsLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBinsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBinsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBinsLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabelErrorBin, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanelBinsLayout.createSequentialGroup()
                .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBinsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogout3))
                    .addGroup(jPanelBinsLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButtonAddBin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBinsLayout.setVerticalGroup(
            jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBinsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonLogout3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBinsLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelErrorBin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButtonAddBin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Metal Bins", jPanelBins);

        jPanelAccounts.setBackground(new java.awt.Color(244, 164, 12));
        jPanelAccounts.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jPanelAccounts.setPreferredSize(new java.awt.Dimension(1000, 500));

        jTableAccount.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAccount.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableAccount);

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACCOUNTS");

        jButtonLogout4.setText("Logout");
        jButtonLogout4.setActionCommand("LOGOUT");

        javax.swing.GroupLayout jPanelAccountsLayout = new javax.swing.GroupLayout(jPanelAccounts);
        jPanelAccounts.setLayout(jPanelAccountsLayout);
        jPanelAccountsLayout.setHorizontalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addGroup(jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogout4)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanelAccountsLayout.setVerticalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLogout4)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Accounts", jPanelAccounts);

        javax.swing.GroupLayout jDialogMenuLayout = new javax.swing.GroupLayout(jDialogMenu.getContentPane());
        jDialogMenu.getContentPane().setLayout(jDialogMenuLayout);
        jDialogMenuLayout.setHorizontalGroup(
            jDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
        );
        jDialogMenuLayout.setVerticalGroup(
            jDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(350, 150));
        setName("login"); // NOI18N
        setResizable(false);

        jPanelBlack.setBackground(new java.awt.Color(51, 51, 51));
        jPanelBlack.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jPanelOrange.setBackground(new java.awt.Color(244, 164, 12));

        jLabelLoginTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLoginTitle.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabelLoginTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabelLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoginTitle.setText("LOGIN");

        jPanelWhite.setBackground(new java.awt.Color(255, 255, 255));

        jPasswordFieldPasswordLogin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jPasswordFieldPasswordLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldEmailLogin.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTextFieldEmailLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonSubmitLogin.setBackground(new java.awt.Color(219, 139, 34));
        jButtonSubmitLogin.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jButtonSubmitLogin.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSubmitLogin.setText("SUBMIT");
        jButtonSubmitLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmitLogin.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMAIL");

        javax.swing.GroupLayout jPanelWhiteLayout = new javax.swing.GroupLayout(jPanelWhite);
        jPanelWhite.setLayout(jPanelWhiteLayout);
        jPanelWhiteLayout.setHorizontalGroup(
            jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWhiteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelWhiteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldPasswordLogin))
                    .addGroup(jPanelWhiteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(jTextFieldEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonSubmitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelWhiteLayout.setVerticalGroup(
            jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWhiteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWhiteLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordFieldPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanelWhiteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSubmitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabelErrorMessage.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelOrangeLayout = new javax.swing.GroupLayout(jPanelOrange);
        jPanelOrange.setLayout(jPanelOrangeLayout);
        jPanelOrangeLayout.setHorizontalGroup(
            jPanelOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrangeLayout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addComponent(jPanelWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrangeLayout.createSequentialGroup()
                .addGroup(jPanelOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOrangeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOrangeLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabelLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        jPanelOrangeLayout.setVerticalGroup(
            jPanelOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrangeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanelWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBlackLayout = new javax.swing.GroupLayout(jPanelBlack);
        jPanelBlack.setLayout(jPanelBlackLayout);
        jPanelBlackLayout.setHorizontalGroup(
            jPanelBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlackLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanelOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelBlackLayout.setVerticalGroup(
            jPanelBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlackLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelOrange.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//  }
    
    /**
     * This method is going to run the JFrame
     * @return 
     */
    public static View showView() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonAddBin;
    javax.swing.JButton jButtonAddMember;
    javax.swing.JButton jButtonDeleteBooking;
    javax.swing.JButton jButtonDeleteMember;
    javax.swing.JButton jButtonLogout1;
    javax.swing.JButton jButtonLogout2;
    javax.swing.JButton jButtonLogout3;
    javax.swing.JButton jButtonLogout4;
    javax.swing.JButton jButtonSubmitLogin;
    javax.swing.JButton jButtonUpdateMember;
    javax.swing.JDialog jDialogMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabelAccount;
    private javax.swing.JLabel jLabelBookingTitle;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDni2;
    private javax.swing.JLabel jLabelEmail;
    javax.swing.JLabel jLabelErrorBin;
    javax.swing.JLabel jLabelErrorBooking;
    javax.swing.JLabel jLabelErrorMember;
    javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelLoginTitle;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanelAccounts;
    javax.swing.JPanel jPanelBins;
    private javax.swing.JPanel jPanelBlack;
    javax.swing.JPanel jPanelBookings;
    javax.swing.JPanel jPanelMembers;
    private javax.swing.JPanel jPanelOrange;
    private javax.swing.JPanel jPanelWhite;
    javax.swing.JPasswordField jPasswordFieldPassword;
    javax.swing.JPasswordField jPasswordFieldPasswordLogin;
    javax.swing.JRadioButton jRadioButtonAdministrator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    javax.swing.JTable jTableAccount;
    javax.swing.JTable jTableBin;
    javax.swing.JTable jTableBooking;
    javax.swing.JTable jTableMember;
    javax.swing.JTable jTableMerge;
    javax.swing.JTextField jTextFieldAccount;
    javax.swing.JTextField jTextFieldCapacity;
    javax.swing.JTextField jTextFieldDni;
    javax.swing.JTextField jTextFieldEmailLogin;
    javax.swing.JTextField jTextFieldEmailMember;
    javax.swing.JTextField jTextFieldIdBin;
    javax.swing.JTextField jTextFieldName;
    javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
